export const actionTypes = {
  ADD_NOTE: "ADD_NOTE",
  CHANGE_TITLE: "CHANGE_TITLE",
  CHANGE_NOTE: "CHANGE_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
  REORDER: "REORDER",
  CLOSE_ALERT: "CLOSE_ALERT",
};
